# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-21 09:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180107_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='_user_following_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='follwers',
            field=models.ManyToManyField(related_name='_user_follwers_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
