# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-21 11:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180121_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follwers',
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='_user_followers_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
