# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-21 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20180121_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='created_dt',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='updated_at',
            new_name='updated_dt',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='created_at',
            new_name='created_dt',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='updated_at',
            new_name='updated_dt',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='created_at',
            new_name='created_dt',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='updated_at',
            new_name='updated_dt',
        ),
    ]
