# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-21 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20180121_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='creator',
        ),
    ]
